# Generated by Django 4.0.6 on 2022-07-28 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classofdevice', '0002_alter_classofdevice_options_and_more'),
        ('companyuse', '0001_initial'),
        ('typeofsi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companycheck', '0001_initial'),
        ('device', '0003_device_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='typeofsi.typeofsi', verbose_name='Тип СИ'),
        ),
        migrations.AddField(
            model_name='device',
            name='who_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companycheck.companycheck', verbose_name='поверитель'),
        ),
        migrations.AddField(
            model_name='device',
            name='who_use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companyuse.companyuse', verbose_name='эксплуатант'),
        ),
        migrations.AlterField(
            model_name='device',
            name='class_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classofdevice.classofdevice', verbose_name='класс технического средства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='права'),
        ),
    ]
