# Generated by Django 4.0.6 on 2022-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOfDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Класс оборудования')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классификация',
                'db_table': 'device_class',
            },
        ),
    ]
