# Generated by Django 4.0.6 on 2022-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Компания-поверитель')),
            ],
            options={
                'verbose_name': 'Поверитель',
                'verbose_name_plural': 'Поверители',
                'db_table': 'company_checks',
            },
        ),
    ]
