# Generated by Django 4.0.6 on 2022-07-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervalcheck', '0002_remove_intervalcheck_name_intervalcheck_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип СИ')),
                ('regNumber', models.CharField(max_length=10, verbose_name='Номер госреестра')),
                ('interval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intervalcheck.intervalcheck')),
            ],
            options={
                'verbose_name': 'Тип СИ',
                'verbose_name_plural': 'Типы СИ',
                'db_table': 'type_of_sis',
            },
        ),
    ]
