# Generated by Django 4.0.6 on 2022-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Интервал проверки')),
            ],
            options={
                'verbose_name': 'Интервал',
                'verbose_name_plural': 'Интервалы',
                'db_table': 'interval_checks',
            },
        ),
    ]
