# Generated by Django 4.0.6 on 2022-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervalcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalcheck',
            name='name',
        ),
        migrations.AddField(
            model_name='intervalcheck',
            name='interval',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Интервал проверки, год'),
            preserve_default=False,
        ),
    ]
